inputDirectory: "/data06/jinwang/isbi/data/bundle_full/dfc_train"
outputDirectory: "/data06/jinwang/journal_2024/output"
numberOfFiberPoints: 25
epochs_pretrain: 450
epochs: 1
pretrain: False
dataset_prepared: True
full_brain: False
fmri_path: "/data06/jinwang/journal_2024/data/processed_data/CC/fmri_fiber_train"
fmri_similarity_path: "/data06/jinwang/journal_2024/data/processed_data/fmri_correlation/CC_7"
dmri_similarity_path: "/data06/jinwang/isbi/data/processed_data/CC/dmri_distance"
strategy_initial: 2
loss_strategy: 2
GPU: 1
pretrained_net_a: "None"
pretrained_net_b: "/data06/jinwang/journal_2024/output/CC_7_initial_test_12_04_23_41_13/output/models/CC_7_initial_test_final_b_k7/model_ep00445_l0.000012.pt"
bundle: "CC_7"
num_clusters: 7
output_name: "CC_7_450_final"
index_pair_path: "/data06/jinwang/journal_2024/data/processed_data/index_pair_bundle.pt"
adj_matrix_path: "/data06/jinwang/isbi/src/DFC_multi_v3_bundle/test/coor_all.pt"
